//===============
// YOMI STREMIO ADDON - CORE LOGIC
// The main entry point for the Stremio logic.
//===============

const { addonBuilder } = require("stremio-addon-sdk");
const { searchAdultAnime, getAnimeMeta, getTrendingAdultAnime, getTopAdultAnime, getJikanMeta } = require("./lib/anilist");
const { searchSukebeiForHentai, cleanTorrentTitle } = require("./lib/sukebei");
const { checkRD, checkTorbox, getActiveRD, getActiveTorbox } = require("./lib/debrid");
const { extractEpisodeNumber, getBatchRange, isEpisodeMatch, selectBestVideoFile } = require("./lib/parser");

let BASE_URL = process.env.BASE_URL || "http://127.0.0.1:7000";
BASE_URL = BASE_URL.replace(/\/+$/, "");

function toBase64Safe(str) {
    return Buffer.from(str, "utf8").toString("base64").replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

function fromBase64Safe(str) {
    return Buffer.from(str.replace(/-/g, '+').replace(/_/g, '/'), "base64").toString("utf8");
}

//===============
// ADDON MANIFEST
//===============
const manifest = {
    id: "org.community.yomi",
    version: "6.8.0",
    name: "Yomi",
    logo: BASE_URL + "/yomi.png", 
    description: "The ultimate Debrid-powered Sukebei gateway. Streams raw, uncompressed Hentai & NSFW Anime directly via Real-Debrid or Torbox.",
    resources: ["catalog", "meta", "stream"],
    types: ["movie", "series"],
    
    idPrefixes: ["anilist:", "sukebei:"],
    catalogs: [
        { id: "sukebei_trending", type: "series", name: "Yomi Trending" },
        { id: "sukebei_top", type: "series", name: "Yomi Top Rated" },
        { id: "sukebei_search", type: "series", name: "Yomi Search", extra: [{ name: "search", isRequired: true }] }
    ],
    // Updated to securely parse the base64 'Yomi' payload generated by the modernized frontend
    config: [
        { key: "Yomi", type: "text", title: "Yomi Internal Payload", required: false }
    ],
    behaviorHints: { configurable: true, configurationRequired: true },
};

const builder = new addonBuilder(manifest);

// Parser explicitly extracts the 'Yomi' key to circumvent standard URI encoding crashes
function parseConfig(config) {
    let parsed = {};
    try {
        if (config && config.Yomi) {
            let b64 = config.Yomi.replace(/-/g, '+').replace(/_/g, '/');
            while (b64.length % 4) { b64 += '='; } 
            const decoded = Buffer.from(b64, "base64").toString("utf8");
            parsed = JSON.parse(decoded);
        } else {
            parsed = config || {};
        }
    } catch (err) {
        console.error("[Config] PARSING ERROR:", err.message);
    }
    return parsed || {};
}

function parseSizeToBytes(sizeStr) {
    if (!sizeStr || typeof sizeStr !== "string") return 0;
    const match = sizeStr.match(/([\d.]+)\s*(GB|MB|KB|GiB|MiB|KiB|B)/i);
    if (!match) return 0;
    const val = parseFloat(match[1]);
    const unit = match[2].toUpperCase();
    if (unit.includes("G")) return val * 1024 * 1024 * 1024;
    if (unit.includes("M")) return val * 1024 * 1024;
    if (unit.includes("K")) return val * 1024;
    return val;
}

function extractTags(title) {
    let res = "SD";
    if (/(1080p|1080|FHD)/i.test(title)) res = "1080p";
    else if (/(720p|720|HD)/i.test(title)) res = "720p";
    else if (/(2160p|4k|UHD)/i.test(title)) res = "4K";
    return { res };
}

// Amatsu logic for extracting the audio/subtitle flags
function extractLanguage(title) {
    const lower = title.toLowerCase();
    if (/(multi|dual|multi-audio|multi-sub)/i.test(lower)) return "MULTI";
    if (/\b(ger|deu|german|deutsch)\b/i.test(lower)) return "GER";
    if (/\b(ita|italian)\b/i.test(lower)) return "ITA";
    if (/\b(fre|fra|french|vostfr|vf)\b/i.test(lower)) return "FRE";
    if (/\b(spa|esp|spanish)\b/i.test(lower)) return "SPA";
    if (/\b(rus|russian)\b/i.test(lower)) return "RUS";
    if (/\b(por|pt-br|portuguese)\b/i.test(lower)) return "POR";
    if (/\b(ara|arabic)\b/i.test(lower)) return "ARA";
    if (/\b(chinese|mandarin|chs|cht|big5)\b|(简|繁|中文字幕)/i.test(lower)) return "CHI";
    if (/\b(kor|korean)\b/i.test(lower)) return "KOR";
    if (/\b(hin|hindi)\b/i.test(lower)) return "HIN";
    if (/\b(pol|polish)\b/i.test(lower)) return "POL";
    if (/\b(nld|dut|dutch)\b/i.test(lower)) return "NLD";
    if (/\b(tur|turkish)\b/i.test(lower)) return "TUR";
    if (/\b(vie|vietnamese)\b/i.test(lower)) return "VIE";
    if (/\b(ind|indonesian)\b/i.test(lower)) return "IND";
    if (/\b(jpn|japanese|raw)\b/i.test(lower)) return "JPN";
    if (/\b(eng|english|subbed)\b/i.test(lower)) return "ENG";
    return "ENG"; 
}

function sanitizeSearchQuery(title) {
    return title.replace(/\(.*?\)/g, "").replace(/\[.*?\]/g, "").replace(/\s{2,}/g, " ").trim();
}

function isTitleMatchingEpisode(title, requestedEp) {
    if (/batch|complete|all\s+episodes/i.test(title)) return true;
    return isEpisodeMatch(title, requestedEp);
}

function generateDynamicPoster(title) {
    let clean = title.replace(/^\[.*?\]\s*/g, "").replace(/\[.*?\]/g, " ").replace(/\(.*?\)/g, " ");
    let safeTitle = clean.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s{2,}/g, " ").substring(0, 30).trim().toUpperCase();
    let words = safeTitle.split(" ");
    let lines = [];
    let line = "";
    for (let word of words) {
        if ((line + word).length > 10) {
            if (line) lines.push(line.trim());
            line = word + " ";
        } else { line += word + " "; }
    }
    if (line) lines.push(line.trim());
    
    return "https://dummyimage.com/600x900/1a1a1a/e91e63.png?text=" + encodeURIComponent(lines.join("\n"));
}

//===============
// STREMIO HANDLERS
//===============

builder.defineCatalogHandler(async ({ id, extra, config }) => {
    console.log("[Catalog Request] Fetching catalog: " + id);
    
    const userConfig = parseConfig(config);
    
    if (id === "sukebei_trending") {
        if (userConfig.showTrending === false) return { metas: [] };
        return { metas: await getTrendingAdultAnime(), cacheMaxAge: 43200 };
    }
    
    if (id === "sukebei_top") {
        if (userConfig.showTop === false) return { metas: [] };
        return { metas: await getTopAdultAnime(), cacheMaxAge: 43200 };
    }
    
    if (id === "sukebei_search" && extra.search) {
        const [anilistMetas, sukebeiTorrents] = await Promise.all([
            searchAdultAnime(extra.search), 
            searchSukebeiForHentai(extra.search)
        ]);
        
        // Amatsu logic for chronological sorting
        anilistMetas.sort((a, b) => {
            const dateA = a.released ? new Date(a.released).getTime() : Infinity;
            const dateB = b.released ? new Date(b.released).getTime() : Infinity;
            return dateA - dateB;
        });

        const finalMetas = [...anilistMetas];
        const rawGroups = {};
        
        sukebeiTorrents.forEach(t => {
            const cleanName = cleanTorrentTitle(t.title);
            if (cleanName.length > 2 && !rawGroups[cleanName]) rawGroups[cleanName] = t;
        });
        
        Object.keys(rawGroups).forEach(cleanName => {
            if (!anilistMetas.some(m => m.name.toLowerCase().includes(cleanName.toLowerCase()))) {
                finalMetas.push({ 
                    id: "sukebei:" + toBase64Safe(cleanName), 
                    type: "series", 
                    name: cleanName.replace(/^\[.*?\]\s*/g, "").trim(), 
                    poster: generateDynamicPoster(cleanName) 
                });
            }
        });
        return { metas: finalMetas, cacheMaxAge: finalMetas.length === 0 ? 60 : 86400 };
    }
    return { metas: [] };
});

builder.defineMetaHandler(async ({ id }) => {
    if (!id.startsWith("anilist:") && !id.startsWith("sukebei:")) {
        return Promise.resolve({ meta: null });
    }

    console.log("[Meta Request] Fetching details for ID: " + id);

    let meta = null;
    let searchTitle = "";

    try {
        if (id.startsWith("anilist:")) {
            const parts = id.split(":");
            let aniListId = parts[1];
            
            if (isNaN(aniListId)) {
                aniListId = parts.find(p => !isNaN(p) && p.length > 0) || parts[1];
            }
	
            const rawMeta = await getAnimeMeta(aniListId);
            	
            if (rawMeta) {
                searchTitle = rawMeta.name;
                meta = {
                    id: id,
                    type: rawMeta.type,
                    name: rawMeta.name,
                    poster: rawMeta.poster,
                    background: rawMeta.background,
                    description: rawMeta.description,
                    releaseInfo: rawMeta.releaseInfo,
                    released: rawMeta.released,
                    episodes: rawMeta.episodes
                };
            } else {
                searchTitle = (parts.length > 2 && parts[2]) 
                    ? fromBase64Safe(parts[2]) 
                    : "Unknown Anime";
                
                meta = { id: id, type: "series", name: searchTitle, poster: generateDynamicPoster(searchTitle) };
            }
        } else if (id.startsWith("sukebei:")) {
            const parts = id.split(":");
            const base64Str = parts[1];
            searchTitle = base64Str ? fromBase64Safe(base64Str) : "Unknown";
            let cleanQuery = searchTitle.replace(/^\[.*?\]\s*/g, "").replace(/\[.*?\]/g, "").replace(/\(.*?\)/g, "").trim();
            const malData = await getJikanMeta(cleanQuery);
            
            if (malData) {
                meta = { 
                    id, 
                    type: "series", 
                    name: searchTitle.replace(/^\[.*?\]\s*/g, "").trim(), 
                    poster: malData.poster || generateDynamicPoster(searchTitle),
                    background: malData.background, 
                    description: malData.description, 
                    releaseInfo: malData.releaseInfo,
                    released: malData.released,
                    episodes: malData.episodes
                };
            } else {
                meta = { id, type: "series", name: searchTitle.replace(/^\[.*?\]\s*/g, "").trim(), poster: generateDynamicPoster(searchTitle) };
            }
        }
        
        meta.type = "series";
        let epCount = meta.episodes || 1;
        if (epCount === 1 || !meta.episodes) {
            console.log("[Meta] Scraping Sukebei to detect actual episode count for OVA/Unknown: " + searchTitle);
            try {
                const torrents = await searchSukebeiForHentai(searchTitle);
                let maxDetected = 1;
                torrents.forEach(t => {
                    const batch = getBatchRange(t.title);
                    if (batch && batch.end > maxDetected && batch.end < 50) maxDetected = batch.end;
                    const ext = extractEpisodeNumber(t.title);
                    if (ext && ext > maxDetected && ext < 50) maxDetected = ext;
                });
                if (maxDetected > epCount) epCount = maxDetected;
            } catch(e) {}
        } else {
            console.log("[Meta] Fast-loading: Episode count known for " + searchTitle + ". Skipping Sukebei scrape.");
        }

        const videos = [];
        const episodeThumbnail = meta.background || meta.poster || "https://dummyimage.com/600x337/1a1a1a/e91e63.png?text=YOMI+EPISODE";
        
        for (let i = 1; i <= epCount; i++) {
            videos.push({ id: meta.id + ":1:" + i, title: "Episode " + i, season: 1, episode: i, released: new Date().toISOString(), thumbnail: episodeThumbnail });
        }
        meta.videos = videos;
        return { meta, cacheMaxAge: 604800 };
    } catch (err) {
        console.error("[Meta Error] Crashed during meta generation: " + err.message);
        return { 
            meta: { id, type: "series", name: "Unknown (Error)", poster: generateDynamicPoster("Error") }, 
            cacheMaxAge: 60 
        };
    }
});

builder.defineStreamHandler(async ({ id, config }) => {
    if (!id.startsWith("anilist:") && !id.startsWith("sukebei:")) return Promise.resolve({ streams: [] });
    
    console.log("[Stream Request] Processing request for ID: " + id);

    try {
        const userConfig = parseConfig(config);
        let searchTitle = "", requestedEp = 1;
        let aniListIdForFallback = null;
        
        if (id.startsWith("anilist:")) {
            const parts = id.split(":");
            aniListIdForFallback = isNaN(parts[1]) ? parts.find(p => !isNaN(p) && p.length > 0) : parts[1];
            
            if (parts.length > 2 && parts[2]) {
                searchTitle = sanitizeSearchQuery(fromBase64Safe(parts[2]));
            } else {
                if (aniListIdForFallback) {
                    const freshMeta = await getAnimeMeta(aniListIdForFallback);
                    if (freshMeta) searchTitle = sanitizeSearchQuery(freshMeta.name);
                }
            }
            
            const lastPart = parts[parts.length - 1];
            if (!isNaN(lastPart) && parts.length > 2) requestedEp = parseInt(lastPart, 10);

        } else if (id.startsWith("sukebei:")) {
            const parts = id.split(":");
            searchTitle = parts[1] ? sanitizeSearchQuery(fromBase64Safe(parts[1])) : "";
            if (parts.length >= 4) requestedEp = parseInt(parts[3], 10);
        }

        if (!searchTitle) {
            console.log("[Stream] Search aborted. No valid title found for ID: " + id);
            return { streams: [] };
        }
        
        console.log("[Stream] Scraping Sukebei for streams: " + searchTitle + " (Episode " + requestedEp + ")");

        let torrents = await searchSukebeiForHentai(searchTitle);
        
        if (!torrents.length) {
            console.log("[Stream] No torrents found for primary title: " + searchTitle + ". Engaging Universal Fallback Engine...");
            
            let fallbackMeta = null;

            if (aniListIdForFallback) {
                fallbackMeta = await getAnimeMeta(aniListIdForFallback);
            } else if (id.startsWith("sukebei:")) {
                let cleanQuery = searchTitle.replace(/^\[.*?\]\s*/g, "").replace(/\[.*?\]/g, "").replace(/\(.*?\)/g, "").trim();
                fallbackMeta = await getJikanMeta(cleanQuery);
            }
            
            if (fallbackMeta) {
                const fallbackTitles = new Set();
                
                if (fallbackMeta.altName && fallbackMeta.altName.length > 2 && fallbackMeta.altName !== searchTitle) {
                    fallbackTitles.add(fallbackMeta.altName);
                }
                
                if (fallbackMeta.synonyms && fallbackMeta.synonyms.length > 0) {
                    fallbackMeta.synonyms.forEach(syn => {
                        if (/^[a-zA-Z0-9\s\-_!:]+$/.test(syn)) fallbackTitles.add(syn);
                    });
                }

                
                // ADVANCED FALLBACK: Truncate long Light Novel titles to bypass Sukebei strict limits
                const primaryWords = searchTitle.split(/\s+/);
                if (primaryWords.length > 3) fallbackTitles.add(primaryWords.slice(0, 3).join(" "));
                if (primaryWords.length > 4) fallbackTitles.add(primaryWords.slice(0, 4).join(" "));
                
                if (fallbackMeta.altName) {
                    const altWords = fallbackMeta.altName.split(/\s+/);
                    if (altWords.length > 3) fallbackTitles.add(altWords.slice(0, 3).join(" "));
                }

                for (const altTitle of fallbackTitles) {
                    console.log("[Stream] Fallback Engine: Searching Sukebei for synonym: " + altTitle);
                    const cleanAlt = sanitizeSearchQuery(altTitle);
                    torrents = await searchSukebeiForHentai(cleanAlt);
                    
                    if (torrents.length > 0) {
                        console.log("[Stream] Success! Found " + torrents.length + " torrents using synonym: " + cleanAlt);
                        break;
                    }
                }
            }
        }

        if (!torrents.length) {
            console.log("[Stream] All searches failed. No streams available.");
            return { streams: [], cacheMaxAge: 60 };
        }

        const hashes = torrents.map(t => t.hash);
        const [rdC, tbC, rdA, tbA] = await Promise.all([
            userConfig.rdKey ? checkRD(hashes, userConfig.rdKey) : {},
            userConfig.tbKey ? checkTorbox(hashes, userConfig.tbKey) : {},
            userConfig.rdKey ? getActiveRD(userConfig.rdKey) : {},
            userConfig.tbKey ? getActiveTorbox(userConfig.tbKey) : {}
        ]);

        const streams = [];
        
        const flags = { 
            "GER": "🇩🇪", "ITA": "🇮🇹", "FRE": "🇫🇷", "SPA": "🇪🇸", "RUS": "🇷🇺", 
            "POR": "🇵🇹", "ARA": "🇸🇦", "CHI": "🇨🇳", "KOR": "🇰🇷", "HIN": "🇮🇳", 
            "POL": "🇵🇱", "NLD": "🇳🇱", "TUR": "🇹🇷", "VIE": "🇻🇳", "IND": "🇮🇩", 
            "JPN": "🇯🇵", "ENG": "🇬🇧", "MULTI": "🌍" 
        };

        torrents.forEach(t => {
            const hashLow = t.hash.toLowerCase();
            const files = rdC[hashLow] || tbC[hashLow];
            
            
            // SEMANTIC UX: Clearly identify if the torrent is a batch release or a single episode
            const isBatch = getBatchRange(t.title) !== null;
            const batchIndicator = isBatch ? "📦 BATCH" : "🎬 EPISODE";
            
            const streamLang = extractLanguage(t.title);
            const flag = flags[streamLang] || "🇬🇧";
            
            let displayTitle = `${flag} Sukebei | ${batchIndicator}\n💾 ${t.size} | 👤 ${t.seeders}`;
            
            let matchedFileName = undefined;

            if (files) {
                const matchedFile = selectBestVideoFile(files, requestedEp);
                if (!matchedFile) return; 
                displayTitle += "\n🎯 File: " + matchedFile.name;
                matchedFileName = matchedFile.name;
            } else {
                if (!isTitleMatchingEpisode(t.title, requestedEp)) return; 
                displayTitle += "\n📄 " + t.title;
            }

            const { res } = extractTags(t.title);
            let langAddon = "";
            if (/(uncensored|decensored)/i.test(t.title)) langAddon = " | Uncen";
            
            const bytes = parseSizeToBytes(t.size);
            
            const buildSubs = (fileList, provider, apiKey, currentEp) => {
                if (!fileList) return [];
                return fileList
                    .filter(f => {
                        const name = f.name || f.path || "";
                        
        				// .idx and .sub (VobSub) are strictly filtered out here as they crash the Stremio web player
                        if (!/\.(ass|srt|ssa|vtt)$/i.test(name)) return false;
                        const extEp = extractEpisodeNumber(name);
                        if (extEp !== null) {
                            return extEp === currentEp;
                        }
                        return isEpisodeMatch(name, currentEp);
                    })
                    .map(f => {
                        let subLang = "English";
                        const n = (f.name || f.path || "").toLowerCase();
                        
                        if (/ger|deu|deutsch/i.test(n)) subLang = "German";
                        else if (/spa|esp|spanish/i.test(n)) subLang = "Spanish";
                        else if (/rus|russian/i.test(n)) subLang = "Russian";
                        else if (/fre|fra|french|vostfr/i.test(n)) subLang = "French";
                        else if (/ita|italian/i.test(n)) subLang = "Italian";
                        else if (/por|portuguese/i.test(n)) subLang = "Portuguese";
                        else if (/pol|polish/i.test(n)) subLang = "Polish";
                        else if (/chinese|chs|cht|big5|简|繁|中文字幕/i.test(n)) subLang = "Chinese";
                        else if (/ara|arabic/i.test(n)) subLang = "Arabic";
                        else if (/jpn|japanese/i.test(n)) subLang = "Japanese";
                        else if (/kor|korean/i.test(n)) subLang = "Korean";
                        else if (/hin|hindi/i.test(n)) subLang = "Hindi";
                        else if (/eng|english/i.test(n)) subLang = "English";

                        const extMatch = n.match(/\.(ass|srt|ssa|vtt)$/);
                        const ext = extMatch ? extMatch[1].toUpperCase() : "SUB";

                        
                        // Append original filename to query to allow correct MIME type parsing for Torbox
                        return { 
                            id: f.id, 
                            url: BASE_URL + "/sub/" + provider + "/" + apiKey + "/" + t.hash + "/" + f.id + "?filename=" + encodeURIComponent(n), 
                            lang: subLang + " (" + ext + ")" 
                        };
                    });
            };

            if (userConfig.rdKey) {
                const fRD = rdC[hashLow];
                const prog = rdA[hashLow];
                const name = (fRD || prog === 100) ? "YOMI [⚡ RD]\n🎥 " + res + langAddon : (prog !== undefined ? "YOMI [⏳ " + prog + "% RD]\n🎥 " + res + langAddon : "YOMI [☁️ RD DL]\n🎥 " + res + langAddon);
                streams.push({ name: name, description: displayTitle, url: BASE_URL + "/resolve/realdebrid/" + userConfig.rdKey + "/" + t.hash + "/" + requestedEp, subtitles: buildSubs(fRD, "realdebrid", userConfig.rdKey, requestedEp), behaviorHints: { notWebReady: true, bingeGroup: "rd_" + t.hash, filename: matchedFileName }, _bytes: bytes, _lang: streamLang });
            }

            if (userConfig.tbKey) {
                const fTB = tbC[hashLow];
                const prog = tbA[hashLow];
                const name = (fTB || prog === 100) ? "YOMI [⚡ TB]\n🎥 " + res + langAddon : (prog !== undefined ? "YOMI [⏳ " + prog + "% TB]\n🎥 " + res + langAddon : "YOMI [☁️ TB DL]\n🎥 " + res + langAddon);
                streams.push({ name: name, description: displayTitle, url: BASE_URL + "/resolve/torbox/" + userConfig.tbKey + "/" + t.hash + "/" + requestedEp, subtitles: buildSubs(fTB, "torbox", userConfig.tbKey, requestedEp), behaviorHints: { notWebReady: true, bingeGroup: "tb_" + t.hash, filename: matchedFileName }, _bytes: bytes, _lang: streamLang });
            }
        });
        
        const rawLangs = userConfig.language || ["ENG"];
        const userLangs = Array.isArray(rawLangs) ? rawLangs : [rawLangs];

        return { 
            streams: streams.sort((a, b) => {
                const getLangScore = (lang) => {
                    if (userLangs.includes(lang) || lang === "MULTI") return 3; 
                    if (lang === "ENG") return 2;                               
                    return 1;                                                   
                };

                const scoreA = getLangScore(a._lang);
                const scoreB = getLangScore(b._lang);
                
                if (scoreA !== scoreB) return scoreB - scoreA;
                
                const aCached = a.name.includes("⚡");
                const bCached = b.name.includes("⚡");
                if (aCached && !bCached) return -1;
                if (!aCached && bCached) return 1;
                return b._bytes - a._bytes;
            }), 
            cacheMaxAge: 5 
        };
    } catch (err) {
        console.error("[Stream Error] Crashed during stream generation: " + err.message);
        return { streams: [] };
    }
});

module.exports = { addonInterface: builder.getInterface(), manifest, parseConfig };
