version: "3.8"

services:
  yomi-addon:
    image: "ghcr.io/mralanbourne/yomi:latest"
    container_name: "yomi_gateway"
    restart: "unless-stopped"
    ports:
      - "7000:7000"

    env_file:
      - ".env"
    environment:
      - "PORT=7000"
      - "NODE_ENV=production"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - "stremio-network"

networks:
  stremio-network:
    name: "stremio-internal-net"
    driver: "bridge"
