# YOMI DOCKER COMPOSE

version: "3.8"

services:
  yomi-addon:
    build: .
    container_name: yomi_gateway
    restart: always
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
    volumes:
      - ./public:/app/public
      - ./static:/app/static
      - ./.env:/app/.env
    networks:
      - yomi-network

networks:
  yomi-network:
    driver: bridge
